djecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('mystore.urls', namespace='mystore')),
    path('api-auth/', include('rest_framework.urls')),

]

handler404 = 'mystore.views.handler_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

mystore/urls.py
from django.urls import path

from .views import *
from . import views
from .api import *

app_name = 'mystore'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_item/', views.add_item, name="add_item"),
    path('product/<slug>/edit_item/', views.edit_item, name='edit_item'),
    path('product/<slug>/delete/', views.delete_item, name='delete_item'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('api/v1/items', ListItem.as_view(), name='items'),
    path('api/v1/items/<int:pk>/', DetailItem.as_view(), name='item'),
    path('<str:room_name>/', views.room, name='room'),
]

mystore/models.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=100, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=10)
    label_text = models.CharField(max_length=50)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_all_items_by_id(category_id):
        if category_id:
            return Item.objects.filter(category=category_id)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("mystore:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("mystore:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("mystore:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.get_total_discount_item_price:
            return self.get_total_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField(max_length=300, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

templates/add_item.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-8 col-lg-7 mx-auto">
                <div class="card my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Add Product</b></h5>
                        <form class="form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ add_item|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-lg btn-outline-info btn-block"
                                        type="submit">Add
                                </button>
                                <br/><br/>
                                <a class="btn btn-dark"
                                   href="/">&#x2190; Go Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Technology Store</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

    </style>
</head>

{% include "navbar.html" %}

<body class="grey lighten-3">

<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include "footer.html" %}
{% include "scripts.html" %}

{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/chatroom.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatroom</label>
                        <textarea class="form-control" id="chat-text" rows="10"></textarea><br>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="input" type="text"></br>
                    </div>
                    <input class="btn btn-secondary btn-lg btn-block" id="submit" type="button" value="Send">
                </form>
            </div>
        </div>
    </div>

    {{ request.user.username|json_script:"user_username" }}
    {{ room_name|json_script:"room-name" }}
    <script>
        const user_username = JSON.parse(document.getElementById('user_username').textContent);
        document.querySelector('#submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': user_username,
            }));
            messageInputDom.value = '';
        };




        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://' +
            window.location.host +
            '/ws/chat/' +
            roomName +
            '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            console.log(data)
            document.querySelector('#chat-text').value += (data.username + ': ' + data.message + '\n')
        }
    </script>

{% endblock content %}

templates/edit_item.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-8 col-lg-7 mx-auto">
                <div class="card my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Edit Product</b></h5>
                        <form class="form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ p_form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-lg btn-outline-info btn-block"
                                        type="submit">Edit
                                </button>
                                <br/><br/>
                                <a class="btn btn-dark"
                                   href="{{ item.get_absolute_url }}">&#x2190; Go Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Laptops</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Computers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Mobiles</a>
            </li>

          </ul>
          <!-- Links -->

        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                  {% if item.image %}
                <img src="{{ item.image.url }}" class="card-img-top">
                  {% endif %}
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">{{ item.label_text }}</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                      <del>{{ item.price }}</del>
                  ${{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Future</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'mystore:add_item' %}" class="nav-link text-black-50" >
                        Add Product
                    </a>
                </li>
            {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'mystore:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'mystore:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'mystore:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'mystore:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">
                  {% if item.image %}

                    <img src="{{ item.image.url }}" class="img-fluid" alt="">
                  {% endif %}

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <h5>
                                <strong>
                                    <strong class="dark-grey-text">{{ item.title }}
                                        <span class="badge badge-pill {{ item.get_label_display }}-color">{{ item.label_text }}</span>
                                    </strong>
                                </strong>
                            </h5>
                            {% if request.user.is_superuser %}
                                <a class="btn btn-light" href="{% url 'mystore:edit_item' item.slug %}">Edit
                                    Product</a>
                                <a class="btn btn-outline-danger" href="{% url 'mystore:delete_item' item.slug %}">Delete</a>
                            {% endif %}


                        </div>


                        <p class="lead">
                            {% if object.discount_price %}
                                <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
                                <span>${{ object.discount_price }}</span>
                            {% else %}
                                <span>${{ object.price }}</span>
                            {% endif %}
                        </p>

                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ object.description }}</p>
                        <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                            Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </a>
                        <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                            Remove from cart
                        </a>

                    </div>
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>


            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    <h2>{{ comment.count }} Comments</h2>

            {% for commentss in comments %}
                        <div class="comments" style="padding: 10px;">
                            <p class="font-weight-bold">
                                {{ commentss.user }}
                                <span class=" text-muted font-weight-normal">
              {{ commentss.timestamp }}
            </span>
                            </p>
                            {{ commentss.comment| linebreaks }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    <h3>Leave a comment</h3>
                    <form method="post" style="margin-top: 1.3em;">
                        {% csrf_token %}
                        {{ comment | crispy }}
                        {% if user.is_authenticated %}
                            <button type="submit" class="btn btn-primary btn-secondary btn-lg">Submit</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary btn-outline-success btn-dark  btn-lg" disabled>
                                Submit
                            </button>
                        {% endif %}
                    </form>
                </div>

            </div>
            <!--Grid column-->

        </div>

    </main>

{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="../static/js/jquery-3.4.1.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="../static/js/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="../static/js/mdb.min.js"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();

</script>